### ISSUE TITLE
Handling of many to many relationships

### ISSUE THREAD

**Issue by Seldaek** [linkorb/haigha#7]
What's the best way to handle m:n bindings? I tried something like:

```
table.object:
    object:
        other_ids: [1,2,3]
```

Which ideally would create the object first then write `($objectId,1), ($objectId, 2), ($objectId, 3)` into the join table `object_other`. I hope it makes sense.

I guess an option would be to do:

```
table.object_other:
    relation_1:
        object_id: 1
        other_id: 1
    relation_2:
        object_id: 1
        other_id: 2
    relation_3:
        object_id: 1
        other_id: 3
```

But that's obviously a lot more verbose.. I might be able to generate it on the fly by extending the TableRecordInstantiator but I thought I'd check with you first.
